### ISSUE TITLE
Storage graph in bucket screen incorrect

### ISSUE THREAD

**Issue by romayalon** [noobaa/noobaa-core#5691]
### Environment info
- NooBaa Version: 5.1
- Platform: N/A

### Actual behavior
1. uploaded 4 files - total logical size is 7G (deduped files).
2. actual size is 480KB.
3. bucket storage graph shows 12G total (logical+free).

### Expected behavior
1. should show actual used + free.

### More information - Screenshots / Logs / Other output
![image](https://user-images.githubusercontent.com/35330373/63756564-44cc6500-c8c1-11e9-9763-1351a1d2ea3a.png)

[nbfedump.2019_08_27-11_45_20.json.gz](https://github.com/noobaa/noobaa-core/files/3545159/nbfedump.2019_08_27-11_45_20.json.gz)

**Comment by nb-ohad** [comment]
The values in the graph are correct (in accordance with the design) but I agree that the graph is very misleading.

This is a data graph, not a storage graph so the values that we show are supposed to be  represented in  "data units". 
- The value of "Used data" is 7GB because the sum of the sizes of all uploaded files is 5GB.
- The value of "Available on internal storage" is 5GB because of 3 reasons: 
1. The storage size of the internal storage is 5GB
2. The actual size written on the internal storage is 480k ~= 0
3. The policy of the bucket is 1 replica so the conversion from "storage units" to "data units" is 5GB/1 = 5GB. Please note that the available size is an estimation of how much we can write on the internal storage in "data units" not "storage units".

If we sum the whole thing we get to ~12GB. 
The reason it looks strange and undecipherable is that the ratio between the files sizes and the actual size of the written blocks is very very large (the files are heavily compressed and deduped)

@nimrod-becker 
Should we close the issue? should it be assigned to @shirimordechay?

**Comment by nimrod-becker** [comment]
As we are not investing in the UI console, closing
