### ISSUE TITLE
Question: pv_pool mirroring 

### ISSUE THREAD

**Issue by yaroslavkasatikov** [noobaa/noobaa-core#6012]
Hello team,

Have a question about mirroring pv_pool.

I have create a PV Pool, all works fine, but the pool size is equat to sum of each volumes. I.e. I have installed PV Pool as STS with 3 Pods with 100G for each and the maximum pool size is 300G. 

1) Is it possible to mirror this pool (Like raid1) and have only 100G as total size?
2) What will happen with Pool if one pod/pvc went down?

**Comment by guymguym** [comment]
Hi @yaroslavkasatikov! 
Thanks for posting your question.

If you mean to use 3 copies between those 3 PVs then this can be done, but currently not exposed from the CRDs APIs. In the UI you can edit the "Data Resiliency Policy" per bucket - see screenshot:

![image](https://user-images.githubusercontent.com/1091422/81497142-43af5c80-92c5-11ea-8c22-9123317dc235.png)

If one of those pods/pvcs is down or corrupted, the mode will change to non-healthy (depending on the causing issue), and since that pool has just 2 healthy nodes, the bucket will become non-writable since it requires 3 copies. Reads will still work. So if you would like to achieve live failure tolerance of 2 volumes, you will need to set the copies to 3 and use 5+ PVs (so that even 2 are down we still have 3 left).

Let me know what other details can assist your design and we can write a doc to describe these capabilities.

**Comment by yaroslavkasatikov** [comment]
Hi @guymguym !
Thank you very much for rapid reply.

1) Number of copies it perfect solution. Thanks.


2)
>  If one of those pods/pvcs is down or corrupted the pool will become non-healthy, and since that pool has just 2 healthy nodes, the bucket will become non-writable since it requires 3 copies. Reads will still work. 

But what will happen with data in this case if 'Number of copies' is 1?  As I understand it become unavaliable until PVs returns. 


And one more question is raise based on you comment:
> but currently not exposed from the CRDs APIs

But in generally can I create buckets from yaml? 

PS: Sorry if some queistions are silly, but it's the first day when I work with NooBaa

Thanks a lot,
Yaroslav

**Comment by guymguym** [comment]
Right, with 1 copy we have no tolerance to unavailable PVs.
The reason this is the default is that many PV providers already provide internal resiliency.
But for a long time we used a default of 3 copies, and this is a very common use case.

You can create buckets from:
- UI
- CLI - `noobaa bucket create`
- CRD (yaml) - ObjectBucketClaim - see this doc https://github.com/noobaa/noobaa-operator/blob/master/doc/obc-provisioner.md

**Comment by yaroslavkasatikov** [comment]
Thanks a lot!
