### ISSUE TITLE
NS-CACHE: < 4k Objects not cached if SS copied or Written out of band (direct upload to hub)

### ISSUE THREAD

**Issue by guptsanj** [noobaa/noobaa-core#6150]
### Environment info
Environment info

NooBaa Version: 5.6
Platform: NA
CC: @guymguym 

### Actual behavior
1. Create a namespace bucket with caching enabled. 
2. Upload a < 4k Object to the hub (not via the namespace bucket)
3. GET object via the namespace bucket (object_api.read_object_md exceptions in s3 log), 
4. GET object via the namespace bucket (same exception again)
A look in the `db.objectmds` collection shows the object was not added to the metadata.

Looks like the object does not get cached 
Same behavior is encountered if a < 4k object is SS Copied or Multi part uploaded to the namespace cache bucket.

### Expected behavior
At the 2nd GET operation, I will expect to see the object is retrieved from the cache 

### Steps to reproduce

See above

**Comment by guptsanj** [comment]
After discussing this with @paulxuzhang , GET object defaults to hub for size <=  `config.INLINE_MAX_SIZE`.
This effectively disables caching for objects < `config.INLINE_MAX_SIZE`.

@guymguym should this still be treated as a bug or as a documentation issue?

**Comment by guymguym** [comment]
I think we can try to use the first_range_data in namespace_cache like we use it in s3_get_object, so that if the entire object is contained in the inline range then we can submit it to cache. Otherwise it's fine to drop it as the cache will anyhow align the read to 0-4MB from hub.

Here is how we handle first_range_data in s3_get_object -
https://github.com/noobaa/noobaa-core/blob/74b79637d8a9a1dca2baf51598860579711a5c6b/src/endpoint/s3/ops/s3_get_object.js#L91-L101

And this is where in namespace_cache we can check if we got object_md.first_range_data from our namespace_hub -
https://github.com/noobaa/noobaa-core/blob/74b79637d8a9a1dca2baf51598860579711a5c6b/src/sdk/namespace_cache.js#L236
