### ISSUE TITLE
S3 default placement only allows none namespaced buckets

### ISSUE THREAD

**Issue by lallinger-arbeit** [noobaa/noobaa-core#6282]
### Environment info
- NooBaa Version: master+30ee3535b5
- Platform: OKD 4.5

### Actual behavior
1. Create a namespaced bucket
2. Create an account, does not matter if "Administrator" or "S3 Access Only"
3. Namespaced bucket can't be selected as "S3 default placement" in dropdown

### Expected behavior
1. Create a namespaced bucket
2. Create an account, does not matter if "Administrator" or "S3 Access Only"
3. Namespaced bucket can be selected as "S3 default placement" in dropdown

### Steps to reproduce
See actual behaviour

**Comment by nimrod-becker** [comment]
I might be mistaken here with your intent, but let me try to explain and see if it makes sense.

When creating buckets we can look at two kinds of APIs :  S3 and NooBaa APIs (rpc, UI, CRDs etc.)
When using the NooBaa APIs you can supply whatever policy you want when you create the bucket, but when using the S3 PutBucket you cannot (which is expected).

For that reason, we added the default placement to accounts, so even if the account uses the S3 PutBucket verb, there is still control of which kind of placement policy the created bucket wold have.

Namespace buckets can only be created via the NooBaa APIs and they can only use namespace resources. Data buckets can only use "regular" resources (non namespace).

Since the idea was to provide a default for creating a bucket via S3 (i.e. non namespace) it doesn't make sense to provide a namespace resource.

We could have thought about adding 2 policies for each account, one for data buckets and one for namespace buckets. Each policy choosing from the relevant resources. I feel this is overkill though, since in order to create a namespace bucket you have to use the NooBaa APIs and can (need) to provide the placement (btw see https://github.com/noobaa/noobaa-operator/pull/464 for k8s control plane APIs for Namespace).

I might have missed you point here, if so would love to continue the discussion.

**Comment by lallinger-arbeit** [comment]
Ah yeah, that makes sense.

I only see this as a minor issue, it might confusing for somebody creating a namespaced resource and then not seeing it in the dropdown.

Some other way to being able to have a default placement on a namespaced bucket would be that noobaa leverages a single namespaced bucket as multiple buckets using prefixes in this bucket. I already have seen this in [Zenko](https://github.com/scality/Zenko). So for example you have one bucket on AWS and from this bucket noobaa could serve multiple buckets, looging like this:
aws-bucket containing:
- noobaa-bucket (a prefix which all files have using this bucket through the noobaa-api, but it is transparent for the noobaa user, who only sees the files without the prefix "noobaa-bucket" but rather in a bucket called noobaa-bucket)
- another-noobaa-bucket

I don't know if i can explain it very well here... I'd be happy to go into more detail today in the community meeting! But this is then not a bug report but rather a feature request (also with very low priority for us)

**Comment by nimrod-becker** [comment]
Fixed in #6466
