### ISSUE TITLE
Log Management

### ISSUE THREAD

**Issue by motorman-ibm** [noobaa/noobaa-core#6417]
### Environment info
- NooBaa Version: noobaa-core-nsfs (probably Nov/Dec 2020 version)
- Platform: Kubernetes 1.19.1

### Actual behavior
Log Management - With Spark I managed to drive Noobaa logs to the point where kubernetes killed the pods due to disk usage - that implies a log management is required for 24x7 running

### Expected behavior
1. Logs are trimmed 

### Steps to reproduce
1. Extended run with high command rate

### More information - Screenshots / Logs / Other output

This was originally part of issue #6272.  I am splitting this out as a separate issue because I believe this is independent of the fix for #6272 and should not be a prerequisite for closing that issue

**Comment by guymguym** [comment]
@motorman-ibm Perhaps this is a kubernetes configuration that's needed to be set.
Not sure yet, but we didn't see this on Openshift AFAIK - right @nimrod-becker ?

**Comment by akmithal** [comment]
Hi @romayalon , @nimrod-becker : Since no where in FVT or real world, we are using Spark workload, so I think instead of closing, we should try this out and then conclude if this needs to be looked at. 
Recently, we saw a bug where Spark used a different SDK that caused endpoint panic, so probably it is worth keeping it open. Thoughts ? 

We have not seen this problem with other workloads like AWS S3 CLI, warp or cosbench.

**Comment by nimrod-becker** [comment]
We can wait to take a decision till such runs are being tested

**Comment by akmithal** [comment]
Hi @nimrod-becker , What do you think we should do with this defect? Would this be amongst our Enhancements list ?

**Comment by nimrod-becker** [comment]
Talking to Akshat and Romy,
We are not aware of such a behavior on top of openshift. The used version contained a lot of issues with stability.

Closing, for now, suggesting to repro on top of openshift with a newer up-to-date version.
