### ISSUE TITLE
Need to have appropriate debug to capture all logs as well as not cause RPC connection failures

### ISSUE THREAD

**Issue by akmithal** [noobaa/noobaa-core#6665]
### Environment info
- NooBaa Version: **VERSION**
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

### Actual behavior
1. -

### Expected behavior
1. No listing failure with higher debug level. 
2. All debug to be captured for debugging

### Steps to reproduce
Please refer to defect #6636  for background information.

We need to have appropriate debug defined so that listing doesn't fail like defect #6636 but should be able to capture all logs for debugging.

**Comment by liranmauda** [comment]
Reopen for Validation
Also related: https://github.com/noobaa/noobaa-operator/pull/706

**Comment by liranmauda** [comment]
Hi @akmithal 
We have done a pre-set of modules as a debug set for NSFS.
This is changing the previous behavior of the env variable `process.env.NOOBAA_LOG_LEVEL`.

Before the change, it was an integer (0...5) and now we created predefined suits, and the values that `process.env.NOOBAA_LOG_LEVEL` can get are `all`, `nsfs`, `warn` or `default_level`. 

In order to change that we have few ways:
1. You can install using the noobaa CLI and the only change is that the `--debug-level` flag gets one of the above values.
  - `--debug-level='default_level': The type of debug sets that the system prints (all, nsfs, warn, default_level)`
2. You can also change the config map with the appropriate value:
  - `kubectl edit configmap/noobaa-config` and set the `NOOBAA_LOG_LEVEL` value to the desired one.
3. You can add it on a specific pod by editing the .env file and adding `NOOBAA_LOG_LEVEL=<logset>` then restart the process

**Comment by akmithal** [comment]
Validated the logs using this way. Closing this bug now. Thanks @liranmauda
