### ISSUE TITLE
Multiple issues when running TPC-DS benchmarks using NooBaa bucket caching

### ISSUE THREAD

**Issue by AlessandroPomponio** [noobaa/noobaa-core#6709]
### Environment info
- NooBaa Version: 
```
INFO[0000] CLI version: 5.9.0                           
INFO[0000] noobaa-image: noobaa/noobaa-core:master-20210725 
INFO[0000] operator-image: noobaa/noobaa-operator:5.9.0
```

- Platform: Kubernetes v1.20.7+IKS

### Actual behavior
1. Create namespace bucket with caching
2. Run TPC-DS benchmarks using the NS bucket endpoint, 100GB of data
3. Test does not complete, multiple errors occur

### Expected behavior
1. Create namespace bucket with caching
2. Run TPC-DS benchmarks using the NS bucket endpoint, 100GB of data
3. Test completes correctly

### Steps to reproduce
1. Create a namespace bucket with caching
2. Run [TPC-DS benchmarks provided by AWS](https://github.com/aws-samples/eks-spark-benchmark) using the NS bucket endpoint, 100GB of data
3. Wait and check the logs

### More information - Screenshots / Logs / Other output
I am trying to run the TPC-DS benchmark provided by AWS on Kubernetes using NooBaa bucket caching to speed up the execution time. With 1 GB of data the benchmark runs successfully but slower than using direct access (~25m execution time vs ~19m), while with 100 GB of data I was able to run it only once (taking 05:54:58 compared to 02:32:50 with direct S3 access). When trying to run it again I encountered a multitude of issues that prevent the benchmark from completing or even sometimes from starting at all. Here is a list of what I found:

- There seems to be a memory leak of sorts in the endpoint, as it crashed with `ENOMEM`.
[noobaa_enomem.log](https://github.com/noobaa/noobaa-core/files/6990880/noobaa_enomem.log)

- Timeout errors and an `INVALID_SCHEMA_DB` for `usagereports`.
[timeout error and INVALID_SCHEMA_DB usagereports.log](https://github.com/noobaa/noobaa-core/files/6990901/timeout.error.and.INVALID_SCHEMA_DB.usagereports.log)

- ~~NooBaa's AWS Access Key stopping working halfway through the benchmark (`NamespaceCache.read_object_md: NOT NoSuchKey in hub InvalidAccessKeyId: The AWS Access Key ID you provided does not exist in our records.`) and causing 403s.
[403 InvalidAccessKeyId.log](https://github.com/noobaa/noobaa-core/files/6990931/403.InvalidAccessKeyId.log)~~
EDIT: please disregard the point above, see first comment.

- `OBJECT_IO_STREAM_ITEM_TIMEOUT` when uploading/reading files
[OBJECT_IO_STREAM_ITEM_TIMEOUT semaphore.log](https://github.com/noobaa/noobaa-core/files/6990986/OBJECT_IO_STREAM_ITEM_TIMEOUT.semaphore.log)

- An error in the BlockAPI: `PutMapping: A big gap was found between id creation and addition to DB`.
[big gap between id creation and addition to db.log](https://github.com/noobaa/noobaa-core/files/6990946/big.gap.between.id.creation.and.addition.to.db.log)

- An error in the cache: `NamespaceCache.read_object_md: error in cache [RpcError: No such object: obj_id undefined`
[no such object obj_id undefined.log](https://github.com/noobaa/noobaa-core/files/6990949/no.such.object.obj_id.undefined.log)

- Errors in the ChunkAPI: `chunk ERROR Error: had chunk errors chunk ChunkAPI , 'Chunk Decoder: missing data frags and no parity'`
[chunk error.log](https://github.com/noobaa/noobaa-core/files/6990967/chunk.error.log)

- `NO_SUCH_RPC_SERVICE` when performing `core.server.node_services.nodes_monitor:: _update_status`
[core_no_such_rpc.log](https://github.com/noobaa/noobaa-core/files/6990972/core_no_such_rpc.log)

- `NO_SUCH_OBJECT`  in `NamespaceS3.read_object_md`
[no such object obj_id undefined.log](https://github.com/noobaa/noobaa-core/files/6990991/no.such.object.obj_id.undefined.log)

Additionally, I have seen these strange behaviors:
- I am unable to change the default backing store for a certain user from the UI: the changes do not get saved. `core.util.postgres_client:: postgres_client: T00006314|Q00429558: failed with error: error: invalid input syntax for type json`
[default storage change.log](https://github.com/noobaa/noobaa-core/files/6990997/default.storage.change.log)

- NooBaa is unable to display statistics for the endpoint and the cache bucket. I do think it is not just a display issue but it's related to the db, see the logs in the following bullet point.
[nbfedump.2021_08_16-11_03_19.json.gz](https://github.com/noobaa/noobaa-core/files/6991040/nbfedump.2021_08_16-11_03_19.json.gz)
[nbfedump.2021_08_16-11_04_29.json.gz](https://github.com/noobaa/noobaa-core/files/6991041/nbfedump.2021_08_16-11_04_29.json.gz)

- A weird anonymous call to azenv.net (???) returning `NoSuchBucket`
[invalid schema db, azenv.log](https://github.com/noobaa/noobaa-core/files/6991009/invalid.schema.db.azenv.log)

- NooBaa does not seem to remove the cached data after the cache TTL has elapsed.

I have attached the pieces of output I had saved before the endpoint crashed and the output of `noobaa diagnose`. I hope they can be sufficient to help you find the issues. If you need additional information, I am more than available to try and help you out.

[noobaa_diagnostics_1629095562.tar.gz](https://github.com/noobaa/noobaa-core/files/6990800/noobaa_diagnostics_1629095562.tar.gz)

**Comment by baum** [comment]
@AlessandroPomponio Thank you! I am in the process of analysis of the log files provided.

Couple of thoughts:

1. Looking at the [`ENOMEM`](https://github.com/noobaa/noobaa-core/files/6990880/noobaa_enomem.log),  accoring to source code, this error occurs while spawning an external process. OS-level error, caused by the Endpoint pod consuming more than pod’s limit.   The endpoint deployment requests/limits pod memory to [`2Gi`](https://github.com/noobaa/noobaa-operator/blob/4c4510e79ac7db909564d5b0524fc7f117476335/deploy/internal/deployment-endpoint.yaml#L41-L47) 
The endpoint deployment is being scaled by  [HPA](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/), see the [HPA declaration](https://github.com/noobaa/noobaa-operator/blob/master/deploy/internal/hpa-endpoint.yaml) currently (a) only the CPU metrics is being used and (b) there is low value for `maxReplicas` defined.  To allow proper scaling, avoiding endpoint pod's memory starvation, could you try tweaking  `noobaa-endpoint` HPA:

    - increase `maxReplicas` significanty, say to 16, in `noobaa-endpoint` HPA
    - define  memory `averageUtilization`, see [here](https://docs.openshift.com/container-platform/4.8/nodes/pods/nodes-pods-autoscaling.html#nodes-pods-autoscaling-creating-memory_nodes-pods-autoscaling)

    I've tried the following procedure  in my test environment to achieve this:
    - For `maxReplicas`,  issue `kubectl edit -n <NAMESPACE_NAME> noobaa noobaa` and change value of `maxCount` under  `endpoints`

    - For memory scaling,  issue `kubectl edit -n <NAMESPACE_NAME>  hpa noobaa-endpoint`,  add under `spec->annotations`:  `autoscaling.alpha.kubernetes.io/metrics: '[{"type":"Resource","resource":{"name":"memory",       "targetAverageUtilization":50}}]'` 
    - To verify: issue `kubectl get hpa -n <NAMESPACE_NAME> `, sample output:
```
NAME              REFERENCE                    TARGETS           MINPODS   MAXPODS   REPLICAS   AGE
noobaa-endpoint   Deployment/noobaa-endpoint   15%/50%, 1%/80%   1         16        1          7m7s
```

2. Looking at `TimeoutError` in [this log](https://github.com/noobaa/noobaa-core/files/6990901/timeout.error.and.INVALID_SCHEMA_DB.usagereports.log), there are timeout errors while performing S3  getObject() from the external S3 endpoint. [See code ref.](https://github.com/noobaa/noobaa-core/blob/3136279e27f2509a0fe87ba9910e217c5d150617/src/sdk/namespace_s3.js#L200-L205). Do you think it is possible that the S3 endpoint is throttling NooBaa endpoint?
```
 Aug-14 11:40:39.262 [Endpoint/9]  [WARN] core.sdk.namespace_s3:: NamespaceS3.read_object_stream: { message: 'Connection timed out after         120000ms', code: 'TimeoutError', time: 2021-08-14T11:40:39.262Z, region: 'us-east-1', hostname: 's3.eu.cloud-object-storage.appdomain.cloud',   retryable: true, statusCode: 206 }
```


Please share your thoughts,
~baum

**Comment by AlessandroPomponio** [comment]
Hello @baum !

1. I have applied your suggestion regarding the HPA and I re-run a benchmark to check if I saw that error again, and I didn't. I saw that the endpoint scaled up to 4 instances, but I must point out that the benchmark did not complete successfully (or even start, actually, I think the installation I have is now KO). The endpoints are consuming respectively 1.43GiB, 997.02MiB, 919MiB and 552.74MiB of RAM and haven't scaled down even though I stopped the benchmark more than 12 hours ago (could this be a problem with releasing RAM?)

2. I've asked about possible throttling by the S3 endpoint (IBM COS) and I've been told this shouldn't be the case (or at least this behavior hasn't presented itself in other tests). 

3. I'm attaching the logs of the benchmark run I've tried yesterday, as I spotted another error: `Aug-31 13:31:51.477 [Endpoint/9]  [WARN] core.rpc.rpc:: RPC._on_response: GOT RESPONSE BUT NO REQUEST reqid 895@n2n://6114e2cecab15600284359e8(1htva879u) connid n2n://6114e2cecab15600284359e8(1htva879u)` 

I'm more than available to provide additional details if need be.
Thanks a lot in advance,
Alessandro

[noobaa-endpoint-798b78fd97-h5zsb_2.log](https://github.com/noobaa/noobaa-core/files/7089730/noobaa-endpoint-798b78fd97-h5zsb_2.log)

**Comment by baum** [comment]
Hello @AlessandroPomponio,

Thank you for providing the new endpoint log file. Still no joy 😪.

My understanding is that there is still memory starvation related issue during the 100G benchmark. NooBaa core limits its memory footprint using [semaphore](https://github.com/noobaa/noobaa-core/blob/master/src/util/semaphore.js) mechanism. The NooBaa semaphore  implements timeouts. The first error I see in the log is `Semaphore Timeout` error, which down the road causes IO errors. IMHO `GOT RESPONSE BUT NO REQUEST` is another side effect of the same issue. Other indications are `A big gap was found between`errors which are still present.

Unfortunately, since node.js process does not return free memory to the OS, so no scaling down is expected. Generally there are discussion about implementing comprehensive Endpoint HPA scaling using custom metrics such as   semaphore WaitQ length and such for upcoming 4.10 release. Meanwhile, as a workaround, to avoid KOing your cluster, you could manually delete running endpoint pods to force scaling down.

In order to deal with the root cause more efforts is required. I'll try to produce a custom core/operator build, which try to handle the load more gracefully. 

Thank you!

**Comment by AlessandroPomponio** [comment]
Thanks a lot  @baum 

I will wait for the custom build, re-run the benchmarks and report back :smiley:
