### ISSUE TITLE
NooBaa will not return HEAD for key=dir1/ if it was not created as dir1/ even if kes=dir1/f1 exists

### ISSUE THREAD

**Issue by eshelmarc** [noobaa/noobaa-core#6764]
### Environment info
- NooBaa Version: **VERSION**
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

### Actual behavior
1.metadata for directory is ignored

### Expected behavior
1.metadata should be set on directory object 

### Steps to reproduce
1.create a directory object directory-name/ that includes metadata

**Comment by eshelmarc** [comment]
I see that if first create dir/ it creates dir/.folder and get HEAD works for dir/  but if I create dir/f1 before creating dir/ get HEAD for dir/ fails, I assume because .folder was not created.

once the .folder is created I see that metadata is saved in .folder and is being returned with get HEAD

so the question is why .folder is not created if key is dir/f1 and for dual access why metadata is not save in dir/ instead of dir/.folder

**Comment by guymguym** [comment]
@eshelmarc Two separate things here:

1. Directories that we create in the FS as a side-effect of putting an object with a key that includes `/` are not considered "real" S3 objects and only exist in the FS, but should not be returned in list-objects and HEAD dir/ should also return NoSuchKey - which was added in PR #6410 and I still think is the right behavior from S3 perspective.

2. For dual access when S3 PUT dir/ works it sets both the meta-data and the data of the put request on the dir/.folder file instead of the directory, while it is possible to set the meta-data on the dir and only the data to a file. I agree that this might be a bit better because it's not very common that S3 PUT is used to send content for a dir/ key, although technically possible. Perhaps we can repurpose this issue to capture this desired change (update the issue title?)
