### ISSUE TITLE
[native] noobaa-core container build is failing

### ISSUE THREAD

**Issue by nik-redhat** [noobaa/noobaa-core#7043]
### Environment info
- NooBaa Version: master
- Platform: **Openshift 4.12**

### Actual behavior
1. The container build of `noobaa-core` is failing on executing the command `npm --nodedir=/usr run build:native`

### Expected behavior
1. The command should succeed and the container should be built correctly.

### Steps to reproduce
1. Try creating a container using this [Dockerfile](https://gitlab.cee.redhat.com/ceph/rhodf/-/blob/rhodf-4.99-rhel-8/distgit/containers/mcg-core/Dockerfile.in)

### More information - Screenshots / Logs / Other output
Build logs can be found [here](https://jenkins-cpaas-rhodf.apps.cpaas-poc.r6c9.p1.openshiftapps.com/job/rhodf-4.99-rhel-8/view/Build%20Jobs/job/rhodf/job/mcg-core-container/job/mcg-core-container/1/console)

**Comment by nik-redhat** [comment]
The issue started happening after the PR #7028 got merged.
cc @liranmauda @baum

**Comment by liranmauda** [comment]
Hi @nik-redhat 
This is a purely Downstream issue.
We are not supporting Upstream builds for s390x and ppc64le arch.

With that in mind, the issue here is that PR https://github.com/noobaa/noobaa-core/pull/7028 presented a code regression, in the compilation and support for s390x and ppc64le arch.

The code regression is easy to fix, all we need to do is take the latest https://github.com/catid/gf256 files into our codebase under the cm256, and update the `version.md`

This will fix the regression, then we should run again and see if the container is getting built for s390x and ppc64le arch.

@baum @nimrod-becker @dannyzaken FYI

I am closing this issue, as it is not supported in the upstream, please open a BZ so we can track that on the Downstream.

**Comment by nik-redhat** [comment]
Ok, when you say Downstream you mean limited to the `release-x.y` branches, correct?

If so, then the issue is that we are running nightly runs on the master branches too and it is tracked under `4.99` version in downstream and for the time being even `4.12` is taking the latest master code. So, the build for both of them are failing.

Also, as of now we don't have this issue in any of the release branches so not sure how will the bz track it, or the BZ is just a reference (something downstream generic) to fix it for the master branch too?

**Comment by liranmauda** [comment]
No, 
Downstream = RedHat builds.
Upstream = Community builds.
No other branch will be affected, Just 5.12
