### ISSUE TITLE
NSFS should return content-type application/x-directory for dirs

### ISSUE THREAD

**Issue by guymguym** [noobaa/noobaa-core#7430]
### Environment info
- NooBaa Version: **5.12**
- Platform: **OpenShift 4.12**

### Actual behavior
1. Currently dirs return applicaiton/octet-stream like any other file.
2. This fails with presto trying to validate it - https://github.com/prestodb/presto/blob/6306290fb92223c51185efdc694f7dcaeb9ff020/presto-hive/src/main/java/com/facebook/presto/hive/s3/PrestoS3FileSystem.java#L377
3. This related PR added the ability to set/get content-type using xattr - #7390 - but this will not work if the directories are created from the FS or replicated from somewhere else.

### Expected behavior
1. Directories should report content-type application/x-directory.

### Steps to reproduce
1. `npm run nsfs .`
2. `mkdir logs`
3. `aws --endpoint http://localhost:6001 s3 cp --content-type applicaiton/x-directory /dev/null s3://logs/dir/`
4. `aws --endpoint http://localhost:6001 s3api head-object --bucket logs --key dir/`

**Comment by khanhn1638** [comment]
we suspect many customers will have already existing data on some s3 bucket somewhere (on-prem or in cloud).  and in order to query this existing dataset, lakehouse admin/user need to create an external table to point to this existing data.

unfortunately this is often enough and running into this issue is painful and tedious.  its not impossible but the steps required to resolve the issue makes it unfriendly.

it would be great if we can prioritize this issue
