### ISSUE TITLE
NSFS | NC | AJV bucket and account schemas should be validated on creation

### ISSUE THREAD

**Issue by romayalon** [noobaa/noobaa-core#7694]
### Environment info
- NooBaa Version: master
- Platform: NC

### Actual behavior
1. bucket and account schemas currently validated on read account/bucket sdk info.

### Expected behavior
1. bucket and account schemas should be validated on add and update as well. bucket creation/update through CLI & bucketspace_fs. account create/update through CLI.

### Steps to reproduce
1.

**Comment by shirady** [comment]
Hi @romayalon,
I have a couple of questions about adding schema validation in `bucketspace_fs`.

1) **Bucket update** - What do you mean by bucket update in the `bucketspace_fs.js` perspective?
2) **Bucket add** - When I checked it using the AWS CLI `aws s3api create-bucket --bucket <bucket-name>` or `s3 mb s3://<bucket-name>` I can see in the flow that the bucket is checked using the schema validation.

I added an error that I caught after the validation (the code changes in PR #7702, note: I removed the full path printings here):
> [LOG] CONSOLE:: SDSD not real error: Error: SDSD check
>     at Object.validate_bucket_schema (noobaa-core/src/server/utils/nsfs_schema_utils.js:36:15)
>     at BucketSpaceFS.read_bucket_sdk_info (noobaa-core/src/sdk/bucketspace_fs.js:133:31)
>     at async NsfsObjectSDK._load_bucket_namespace (noobaa-core/src/sdk/object_sdk.js:283:41)
>     at async LRUCache._load_item (/noobaa-core/src/util/lru_cache.js:83:22)
>     at async LRUCache.get_with_cache (noobaa-core/src/util/lru_cache.js:72:13)
>     at async NsfsObjectSDK.read_bucket_sdk_config_info (noobaa-core/src/sdk/object_sdk.js:179:28)
>     at async Object.send_bucket_op_logs (noobaa-core/src/endpoint/s3/s3_bucket_logging.js:10:29)
>     at async handle_request (noobaa-core/src/endpoint/s3/s3_rest.js:154:9)
>     at async Object.s3_rest [as handler] (noobaa-core/src/endpoint/s3/s3_rest.js:65:9)

It happens since we get to `_load_bucket_namespace` with `params.bucket` `undefined`:
https://github.com/noobaa/noobaa-core/blob/d18db4308db95df162ebe10b442cf110aae0f2fd/src/sdk/object_sdk.js#L281-L285

Hence, at this point, I didn't add a call to `validate_bucket_schema` function from `create_bucket` in `bucketspace_fs.js`.

**Comment by romayalon** [comment]
@shirady 
1.  Bucket update - every function where the bucket config file is being updated
2. not sure I understand your suggestion, we need to validate_bucket_schema on bucket creation, _load_bucket_namespace() called from send_bucket_op_logs() is being called after the op finished

**Comment by shirady** [comment]
@romayalon thanks, since I need to define the cases of the bucket update, and I need to add the schema validation to bucket creation, I would separate the PRs:
(1) for CLI operations (WIP)
(2) for `bucketspace_fs`

**Comment by shirady** [comment]
@romayalon I tried to map the calls to a change in bucket configuration in file `bucketspace_fs`, there will be some changes to the current `nsfs_bucket_schema`, please share your thoughts:
Add bucket - `create_bucket`.
Update bucket:
1. `set_bucket_versioning` property: `versioning`.
2. `put_bucket_tagging` property: `tag` -> the function is not implemented yet.
3. `put_bucket_website`  property: `website` -> We don't have the property `website` in our schema.
     I'm planning to use the definition: `$ref: 'common_api#/definitions/bucket_website'`
4. `put_bucket_policy` property: `s3_policy`.
5. `put_bucket_encryption` property: `encryption` -> We don't have the property `encryption` in our schema.
      I'm planning to use the definition: `$ref: 'common_api#/definitions/bucket_encryption'`
6. The rest of the properties are set/changed in the `new_bucket_defaults`: `name`, `system_owner`, `bucket_owner`, `path`, `should_create_underlying_storage`, `creation_date`, `fs_backend`.
Also, `owner_account` will be ignored (and not added to the `nsfs_bucket_schema`).

**Comment by romayalon** [comment]
@shirady 
if something is missing in the schema it needs to be added ofc.
please don't forget to update the relevant docs on every schema changes.

**Comment by shirady** [comment]
The PRs of validation
1. CLI operations #7702 
2. `bucketspace_fs` #7710 
were added to PR #7544
