### ISSUE TITLE
CI | Nightly RPM Build - Master Branch - Fails (Arch `ppc64le`)

### ISSUE THREAD

**Issue by shirady** [noobaa/noobaa-core#8575]
### Environment info
- NooBaa Version: current, 5.18.0
- Platform: CI, Github workflow

### Actual behavior
1.  Nightly RPM Build - Master Branch Fails

### Expected behavior
1.  Nightly RPM Build - Master Branch should not fail.

### Steps to reproduce
1. I saw it in our actions:
https://github.com/noobaa/noobaa-core/actions/workflows/nightly-rpm-master-build.yaml

### More information - Screenshots / Logs / Other output
When looking inside we can see that it comes from:
call-master-rpm-build-and-upload / build-rpm-centos9-ppc64le / rpm-build-and-upload-artifact

In the step: "Finalize RPM"

> 0s
> Run DATE=$(date +'%Y%m%d')
> rpm_full_path=noobaa-core-5.[1](https://github.com/noobaa/noobaa-core/actions/runs/12149636040/job/33880739772#step:7:1)8.0-20241204-master.el9.ppc64le.rpm
> cp: cannot stat './build/rpm/noobaa-core-5.18.0-20241204.el9.ppc64le.rpm': No such file or directory
> Error: Process completed with exit code 1

**Comment by naveenpaul1** [comment]
all the nightly build starts at one hr before midnight, in this example its `2024-12-15T23:00:00` : [Job](https://github.com/noobaa/noobaa-core/actions/runs/12342996980/job/34443493785)
```
2024-12-15T23:01:24.1234323Z ##[group]Run echo "Starting make rpm"
```
because of that RPM will have version specific to that date
```
2024-12-15T23:19:20.1637229Z [36m+ main@./packagerpm.sh:14 [0mrevision=20241215
```
But the complete rpm build is taking more than 1hr and right before upload date changes to `2024-12-16`
```
2024-12-16T00:03:42.5687764Z Make rpm completed
```
and `Finalize Rpm` step is expecting the rpm with next date `2024-12-16`
```
2024-12-16T00:03:42.6105332Z rpm_full_path=noobaa-core-5.18.0-20241216-master.el9.ppc64le.rpm
2024-12-16T00:03:42.6119939Z cp: cannot stat './build/rpm/noobaa-core-5.18.0-20241216.el9.ppc64le.rpm': No such file or directory
```
It was working before only because `make rpm` was taking less than 1Hr to complete : [job](https://github.com/noobaa/noobaa-core/actions/runs/11430336120/job/31797772836)

Solution would be starts the build at midnight `2024-12-16T00:00:00`
@romayalon @shirady
